config/routes.rb
Rails.application.routes.draw do

    resources :bucket_lists do
        resources :bucket_items do
            member do
                patch :complete
            end
        end
    end

    root :to => "bucket_lists#index"

end

app/models/bucket_item.rb
class BucketItem < ActiveRecord::Base
    
    belongs_to :bucket_list

    def completed?
        !completed_at.blank?
    end

end

app/models/bucket_list.rb
class BucketList < ActiveRecord::Base

    has_many :bucket_items, dependent: :destroy
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/bucket_items_controller.rb
class BucketItemsController < ApplicationController
    before_action :set_bucket_list
    before_action :set_bucket_item, except: [:create]

    def create
        @bucket_item = @bucket_list.bucket_items.create(bucket_item_params)

        redirect_to @bucket_list
    end

    def destroy
        @bucket_item = @bucket_list.bucket_items.find(params[:id])
        if @bucket_item.destroy
            flash[:success] = "Bucket List item was deleted, good luck replacing that one with something better"
        else
            flash[:error] = "Bucket List couldn' t be deleted due to an error."
        end
        redirect_to @bucket_list
    end


    def complete
        @bucket_item.update_attribute(:completed_at, Time.now)
        redirect_to @bucket_list, notice: "Bucket List Item Accomplished"
    end




    private

    def set_bucket_list
        @bucket_list = BucketList.find(params[:bucket_list_id])
    end

    def set_bucket_item
        @bucket_item = @bucket_list.bucket_items.find(params[:id])
    end

    def bucket_item_params
        params[:bucket_item].permit(:content)
    end


end

app/controllers/bucket_lists_controller.rb
class BucketListsController < ApplicationController
    before_action :set_bucket_list, only: [:show, :edit, :update, :destroy]


    def index
        @bucket_lists = BucketList.all
    end


    def show
    end

    def new
        @bucket_list = BucketList.new
    end

    def edit
    end

    def create
        @bucket_list = BucketList.new(bucket_list_params)

        respond_to do |format|
            if @bucket_list.save
                format.html { redirect_to @bucket_list, notice: 'Bucket list was successfully created.' }
                format.json { render :show, status: :created, location: @bucket_list }
            else
                format.html { render :new }
                format.json { render json: @bucket_list.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @bucket_list.update(bucket_list_params)
                format.html { redirect_to @bucket_list, notice: 'Bucket list was successfully updated.' }
                format.json { render :show, status: :ok, location: @bucket_list }
            else
                format.html { render :edit }
                format.json { render json: @bucket_list.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @bucket_list.destroy
        respond_to do |format|
            format.html { redirect_to root_url, notice: 'Bucket list was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    def set_bucket_list
        @bucket_list = BucketList.find(params[:id])
    end

    def bucket_list_params
        params.require(:bucket_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/bucket_items_helper.rb
module BucketItemsHelper
    
end

app/helpers/bucket_lists_helper.rb
module BucketListsHelper
    
end

app/views/bucket_items/_bucket_item.html.erb
<div class="row clearfix">
    <% if bucket_item.completed? %>
    <div class="complete">
        <%= link_to complete_bucket_list_bucket_item_path(@bucket_list, bucket_item.id), method: :patch do %>
        <i style="opacity: 0.3;" class="fa fa-check" ></i>
        <% end %>
    </div>
    <div class="bucket_item">
        <p style="opacity: 0.3;"><strike style="color: #4d4d4d;"><%= bucket_item.content %></strike></p>
    </div>
    <div class="trash">
        <%= link_to bucket_list_bucket_item_path(@bucket_list, bucket_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash"></i>
        <% end %>
    </div>
    <% else %>
    <div class="complete">
        <%= link_to complete_bucket_list_bucket_item_path(@bucket_list, bucket_item.id), method: :patch do %>
        <i class="fa fa-check"></i>
        <% end %>
    </div>
    <div class="bucket_item">
        <p><%= bucket_item.content %></p>
    </div>
    <div class="trash">
        <%= link_to bucket_list_bucket_item_path(@bucket_list, bucket_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash"></i>
        <% end %>
    </div>
    <% end %>
</div>

app/views/bucket_items/_form.html.erb
<%= form_for([@bucket_list, @bucket_list.bucket_items.build]) do |f| %>
    <%= f.text_field :content, placeholder: "Enter New Here" %>
    <%= f.submit %>
<% end %>

app/views/bucket_lists/_form.html.erb
<%= form_for(@bucket_list) do |f| %>

<% if @bucket_list.errors.any? %>

<div id="error_explanation">
    <h2><%= pluralize(@bucket_list.errors.count, "error") %> prohibited this bucket_list from being saved:</h2>

    <ul>
        <% @bucket_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>

<% end %>

<div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</div>
<div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
</div>
<div class="actions">
    <%= f.submit %>
</div>

<% end %>

app/views/bucket_lists/edit.html.erb
<h1 class="bucket_list_title">Edit Bucket List</h1>

<div class="forms">
    <%= render 'form' %>
</div>

<div class="links">
    <%= link_to 'Cancel', bucket_lists_path %>
</div>

app/views/bucket_lists/index.html.erb
<% @bucket_lists.each do |bucket_list| %>
<div class="index_row clearfix">
    <h2 class="bucket_list_title"><%= link_to bucket_list.title, bucket_list %></h2>
    <p class="bucket_list_sub_title"><%= bucket_list.description %></p>
</div>
<% end %>

<div class="links">
    <h2><%= link_to "Create A New Bucket List Here", new_bucket_list_path %></h2>
</div>

app/views/bucket_lists/new.html.erb
<h1 class="bucket_list_title">Bucket List</h1>

<div class="forms">
    <%= render 'form' %>
</div>

<div class="links">
    <%= link_to 'Back', bucket_lists_path %>
</div>

app/views/bucket_lists/show.html.erb
<h2 class="bucket_list_title"><%= @bucket_list.title %></h2>
<h4 class="bucket_list_sub_title"><%= @bucket_list.description %></h4>

<p id="notice"><%= notice %></p>
<div id="bucket_items_wrapper">
    <%= render @bucket_list.bucket_items %>
    <div id="form">
        <%= render "bucket_items/form" %>
    </div>
</div>

<div class="links">
    <h4>
        <%= link_to 'Edit', edit_bucket_list_path(@bucket_list) %> |
        <%= link_to 'Delete', bucket_list_path(@bucket_list), method: :delete, data: { confirm: "Are you sure?" }%> |
        <%= link_to 'Back', bucket_lists_path %>
    </h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Bucket List</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Abril+Fatface:400,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <h1><%= link_to "Bucket List", "/" %></h1>

    <div class="container">
        <%= yield %>
    </div>



    <div class="row">
        <div class="col-xs-12" style="color: #fff; text-align: center">
            <hr>
            <h3>::::: Built by <a href="http://www.ryanurie.com" target="_blank">Ryan Urie / Nerd Life </a>:::::</h3>
        </div>
    </div>  <!-- /.container -->


</body>
</html>